/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasbihRouteImport } from './routes/tasbih'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuranIndexRouteImport } from './routes/quran.index'
import { Route as AzkarIndexRouteImport } from './routes/azkar.index'
import { Route as QuranNumRouteImport } from './routes/quran.$num'
import { Route as AzkarIdRouteImport } from './routes/azkar.$id'

const TasbihRoute = TasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/quran/',
  path: '/quran/',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarIndexRoute = AzkarIndexRouteImport.update({
  id: '/azkar/',
  path: '/azkar/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranNumRoute = QuranNumRouteImport.update({
  id: '/quran/$num',
  path: '/quran/$num',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarIdRoute = AzkarIdRouteImport.update({
  id: '/azkar/$id',
  path: '/azkar/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/hadith': typeof HadithRoute
  '/missions': typeof MissionsRoute
  '/qibla': typeof QiblaRoute
  '/settings': typeof SettingsRoute
  '/tasbih': typeof TasbihRoute
  '/azkar/$id': typeof AzkarIdRoute
  '/quran/$num': typeof QuranNumRoute
  '/azkar/': typeof AzkarIndexRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/hadith': typeof HadithRoute
  '/missions': typeof MissionsRoute
  '/qibla': typeof QiblaRoute
  '/settings': typeof SettingsRoute
  '/tasbih': typeof TasbihRoute
  '/azkar/$id': typeof AzkarIdRoute
  '/quran/$num': typeof QuranNumRoute
  '/azkar': typeof AzkarIndexRoute
  '/quran': typeof QuranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/hadith': typeof HadithRoute
  '/missions': typeof MissionsRoute
  '/qibla': typeof QiblaRoute
  '/settings': typeof SettingsRoute
  '/tasbih': typeof TasbihRoute
  '/azkar/$id': typeof AzkarIdRoute
  '/quran/$num': typeof QuranNumRoute
  '/azkar/': typeof AzkarIndexRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/hadith'
    | '/missions'
    | '/qibla'
    | '/settings'
    | '/tasbih'
    | '/azkar/$id'
    | '/quran/$num'
    | '/azkar/'
    | '/quran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/hadith'
    | '/missions'
    | '/qibla'
    | '/settings'
    | '/tasbih'
    | '/azkar/$id'
    | '/quran/$num'
    | '/azkar'
    | '/quran'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/hadith'
    | '/missions'
    | '/qibla'
    | '/settings'
    | '/tasbih'
    | '/azkar/$id'
    | '/quran/$num'
    | '/azkar/'
    | '/quran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  HadithRoute: typeof HadithRoute
  MissionsRoute: typeof MissionsRoute
  QiblaRoute: typeof QiblaRoute
  SettingsRoute: typeof SettingsRoute
  TasbihRoute: typeof TasbihRoute
  AzkarIdRoute: typeof AzkarIdRoute
  QuranNumRoute: typeof QuranNumRoute
  AzkarIndexRoute: typeof AzkarIndexRoute
  QuranIndexRoute: typeof QuranIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasbih': {
      id: '/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof TasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/quran'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar/': {
      id: '/azkar/'
      path: '/azkar'
      fullPath: '/azkar/'
      preLoaderRoute: typeof AzkarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/$num': {
      id: '/quran/$num'
      path: '/quran/$num'
      fullPath: '/quran/$num'
      preLoaderRoute: typeof QuranNumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar/$id': {
      id: '/azkar/$id'
      path: '/azkar/$id'
      fullPath: '/azkar/$id'
      preLoaderRoute: typeof AzkarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  HadithRoute: HadithRoute,
  MissionsRoute: MissionsRoute,
  QiblaRoute: QiblaRoute,
  SettingsRoute: SettingsRoute,
  TasbihRoute: TasbihRoute,
  AzkarIdRoute: AzkarIdRoute,
  QuranNumRoute: QuranNumRoute,
  AzkarIndexRoute: AzkarIndexRoute,
  QuranIndexRoute: QuranIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
